x-common-variables: &common-variables
  SECRET_KEY: your_secret_key
  DEBUG: true
  DATABASE_NAME: postgres
  DATABASE_USER: postgres
  DATABASE_PASSWORD: postgres
  DATABASE_HOST: db
  DATABASE_PORT: 5432
  USE_MOCK_DATA: True
  OPENAI_API_KEY: your_openai_api_key
  AWS_ACCESS_KEY_ID: your_aws_access_key
  AWS_SECRET_ACCESS_KEY: your_aws_secret_key
  AWS_STORAGE_BUCKET_NAME: your_s3_bucket_name
  REDIS_PORT: 6379
  REDIS_HOST: redis

services:
  app:
    build:
      context: .
    environment:
      <<: *common-variables
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    depends_on:
      - db
      - redis

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres"]
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  pgdata:
    driver: local
