# Generated by Django 5.1.1 on 2024-11-05 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0005_remove_profile_created_at_post_video_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video_url',
        ),
    ]
