# Generated by Django 5.1.1 on 2024-10-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoprompt',
            name='category',
            field=models.CharField(choices=[('comedy', 'Comedy'), ('tragedy', 'Tragedy'), ('humor', 'Humor'), ('romance', 'Romance'), ('horror', 'Horror')], default='comedy', max_length=10),
        ),
    ]
